# Latest here : https://github.com/flowerey/flower-mpv-config

# Quality settings
profile=fast
vo=gpu-next
hwdec=vaapi-copy
#vf=format=yuv420p

#icc-profile="/home/zek/.color/Color LCD-DB334F0D-2236-5803-9C06-66A1DC1411D5.icc"

osd-font="AporeticSerifMonoNerdFont"

watch-later-options-remove=sub-pos
watch-later-options-remove=osd-margin-y

script-opts-append=autocrop-auto=no

osc=no

scale-antiring=0.6

# Saves position on quit so you won't lose progress
keep-open=yes
save-position-on-quit

# Screenshot settings
screenshot-dir="~/Pictures/mpv" # Pictures\mpv in Windows
screenshot-format=png
screenshot-png-compression=9
screenshot-template="%f-%P-%n"
screenshot-high-bit-depth=no

## Language Priority
## Sub
## Add enm before en for honorifics
slang=en,eng
alang=ja,jpn

## Dub
#slang=zxx,en,eng
#alang=en,eng
#subs-with-matching-audio=forced

# Font override
# If you want to change the font, change sub-font to the font name (not file name!). And put
# your font file in fonts folder. Make you sure put every version (or whatever you call it)
# like Bold, Regular, Italic etc. or it won't work correctly.
# Set sub-ass-override to "no" as we only need to enable it for specific cases
sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080
sub-font="AporeticSerifMonoNerdFont" # CHANGE THIS
sub-font-size=20
sub-color="#FFFFFF"
sub-margin-y=20
sub-border-size=1
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-bold=yes
sub-ass-style-overrides=Kerning=yes

# Manga profile
[Manga]
profile-desc="Read Manga"
profile-cond=filename and filename:match('%.cbz$') or filename:match('%.cbr$') or filename:match('%.zip$') or filename:match('%.rar$') ~= nil
profile=high-quality
dscale=mitchell
deband=no

# Some other profiles (for WEB streams)
[crunchyroll]
profile-cond=filename:match("SubsPlease") or filename:match("HorribleSubs")
profile-restore=copy
sub-ass-use-video-data=aspect-ratio

[simulcast]
profile-cond=(function(a)for b,c in ipairs(a)do if filename:match(c)then return true end end end)({"SubsPlease","Erai%-raws","Tsundere%-Raws","%-VARYG","HorribleSubs","SubsPlus%+", "Yameii"})
profile-restore=copy
deband=yes
