[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = false

# Modified colors.css to take RGB values instead for me to modify its transparency in the configs

# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
# You could also set a static color if you use the color keywords and the wallpaper setter supports it.
command = "awww img --transition-type center '{{ image }}'"

#[templates.shipfetch]
#input_path = '~/.config/matugen/templates/current'
#post_hook = 'magick mogrify -path /home/zek/scripts/shipfetch/assets/ -gamma 1.75 -fill "{{colors.primary.default.hex}}" -tint 80 /home/zek/scripts/shipfetch/assets/base/*.png'

# Implemented this so that the currently used color can be cat'ed
[templates.currentcolor]
input_path = '~/.config/matugen/templates/current'
output_path = '~/.config/matugen/current-color'

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/adw-gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
[templates.gtk4]
input_path = '~/.config/matugen/templates/adw-gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.micro]
input_path = '~/.config/matugen/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.swaync]
input_path = "~/.config/matugen/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -R -rs"

[templates.wlogout]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/wlogout/colors.css'
pre_hook = """sed -i 's/fill="[^"]*"/fill="{{ colors.primary.default.hex }}"/g' $HOME/.config/wlogout/icons/*.svg"""

[templates.kcolorscheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'
[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'
[templates.kvantum_svg]
input_path = './templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

# Universal terminal colors and a good color palette for them (from https://github.com/InioX/matugen-themes/pull/132)
[templates.term-colors]
input_path = "~/.config/matugen/templates/term-colors.json"
output_path = "~/.cache/matugen/term-colors.json"
post_hook = "python ~/.config/matugen/post-hook-scripts/generate-term-colors.py ~/.cache/matugen/term-colors.json"
# Provided as a fallback
[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.config/foot/matugen.ini'

# Modified
[templates.mango]
input_path = '~/.config/matugen/templates/mango.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = 'mmsg dispatch reload_config'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

# Modified
[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.papirus-folders]
input_path = '~/.config/matugen/templates/papirus-color'
colors_to_compare = [
    { name = "black",      color = "#4f4f4f" },
    { name = "blue",       color = "#5294e2" },
    { name = "bluegrey",   color = "#607d8b" },
    { name = "brown",      color = "#ae8e6c" },
    { name = "carmine",    color = "#a30002" },
    { name = "cyan",       color = "#00bcd4" },
    { name = "darkcyan",   color = "#45abb7" },
    { name = "deeporange", color = "#eb6637" },
    { name = "green",      color = "#87b158" },
    { name = "grey",       color = "#8e8e8e" },
    { name = "indigo",     color = "#5c6bc0" },
    { name = "magenta",    color = "#ca71df" },
    { name = "nordic",     color = "#81a1c1" },
    { name = "orange",     color = "#ee923a" },
    { name = "palebrown",  color = "#d1bfae" },
    { name = "paleorange", color = "#eeca8f" },
    { name = "pink",       color = "#f06292" },
    { name = "red",        color = "#e25252" },
    { name = "teal",       color = "#16a085" },
    { name = "violet",     color = "#7e57c2" },
    { name = "white",      color = "#e4e4e4" },
    { name = "yaru",       color = "#676767" },
    { name = "yellow",     color = "#f9bd30" },
]
compare_to = "{{ colors.primary.default.hex }}"
post_hook = 'nohup sudo -n papirus-folders -C {{ closest_color }} -u > /dev/null 2>&1 &'
index = 1
