#                                  
#      ▄▄▄▄▄▄                      
#     █▀ ██                     █▄ 
#        ██   ▄                ▄██▄
#        ██   ████▄ ████▄ ██ ██ ██ 
#        ██   ██ ██ ██ ██ ██ ██ ██ 
#      ▄▄██▄▄▄██ ▀█▄████▀▄▀██▀█▄██ 
#                   ██             
#                   ▀              

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us
xkb_rules_model=macbook

# Trackpad
# need relogin to make it apply
disable_trackpad=0
trackpad_accel_profile=1
trackpad_accel_speed=0.45
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=0
left_handed=0
middle_button_emulation=0
swipe_min_threshold=0.1
trackpad_scroll_factor=0.4

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
mouse_accel_profile=1
mouse_accel_speed=-0.75
