#                                                                       
#      ▄▄▄                                ▄▄▄▄▄▄         ▄▄             
#     ▀██▀                               █▀██▀▀▀█▄        ██            
#      ██                        ▄         ██▄▄▄█▀        ██            
#      ██      ▄▀▀█▄ ██ ██ ▄█▀█▄ ████▄     ██▀▀█▄   ██ ██ ██ ▄█▀█▄ ▄██▀█
#      ██      ▄█▀██ ██▄██ ██▄█▀ ██      ▄ ██  ██   ██ ██ ██ ██▄█▀ ▀███▄
#     ████████▄▀█▄██▄▄▀██▀▄▀█▄▄▄▄█▀      ▀██▀  ▀██▀▄▀██▀█▄██▄▀█▄▄▄█▄▄██▀
#                      ██                                               
#                    ▀▀▀                                                

layerrule=animation_type_open:fade,animation_type_close:fade,layer_name:launcher

layerrule=noanim:1,layer_name:waybar
layerrule=noanim:1,noshadow:1,layer_name:swaync

windowrule=allow_csd:0,appid:librewolf
windowrule=isterm:1,appid:foot
windowrule=isterm:1,appid:gtk-youtube-viewer
