#                                                       
#         ▄▄                                            
#       ▄█▀▀█▄         █▄             █▄             █▄ 
#       ██  ██        ▄██▄           ▄██▄      ▄    ▄██▄
#       ██▀▀██   ██ ██ ██ ▄███▄ ▄██▀█ ██ ▄▀▀█▄ ████▄ ██ 
#     ▄ ██  ██   ██ ██ ██ ██ ██ ▀███▄ ██ ▄█▀██ ██    ██ 
#     ▀██▀  ▀█▄█▄▀██▀█▄██▄▀███▀█▄▄██▀▄██▄▀█▄██▄█▀   ▄██ 
#                                                       
#                                                       

exec-once=wlsunset -l 13.6 -L 121.1 -t 3700
exec-once=waybar
exec=killall swaybg ; swaybg -m fill -i "/home/zek/Downloads/__raiden_shogun_and_yae_miko_genshin_impact_drawn_by_o0dyw0o__ad928c4449e486a1ecddaf61ba0262b2.jpg"

exec-once=/usr/lib/xdg-desktop-portal-wlr
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#exec-once=swayosd-server

exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once=wl-paste --type text --watch cliphist store

exec-once=kdeconnectd
exec-once=kdeconnect-indicator
exec-once=nm-applet
