rootcolor=fff8f7ff

bordercolor=d6c2c4ff

splitcolor=d6c2c4ff

focuscolor=8e4958ff

dropcolor=ffb2bfff

maximizescreencolor=75565bff

urgentcolor=ba1a1aff

scratchpadcolor=7a5832ff

globalcolor=75565bff

overlaycolor=7a5832ff
