rootcolor=fff8f7ff

bordercolor=dac0c3ff

splitcolor=dac0c3ff

focuscolor=bc004eff

dropcolor=ffb2bfff

maximizescreencolor=82524cff

urgentcolor=ba1a1aff

scratchpadcolor=8a4f34ff

globalcolor=82524cff

overlaycolor=8a4f34ff
