rootcolor=fff8f8ff

bordercolor=d8c1c8ff

splitcolor=d8c1c8ff

focuscolor=b70073ff

dropcolor=ffb0d0ff

maximizescreencolor=7f525bff

urgentcolor=ba1a1aff

scratchpadcolor=8b4c4cff

globalcolor=7f525bff

overlaycolor=8b4c4cff
