# More option see https://github.com/DreamMaoMao/mango/wiki/

source-optional=./colors.conf
source-optional=./modules/env.conf
source-optional=./modules/start.conf
source-optional=./modules/decor.conf
source-optional=./modules/input.conf
source-optional=./modules/binds.conf
source-optional=./modules/layout.conf
source-optional=./modules/rules.conf

monitorrule=name:^LVDS-1$,refresh:60,width:1280,height:800,custom:1

# Misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=0
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
cursor_size=22
cursor_hide_on_keypress=1
cursor_hide_timeout=0
cursor_theme=Bibata-Modern-Ice
drag_tile_to_tile=1
drag_tile_small=1
