# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#25181d"

# Title color for boxes
theme[title]="#b70073"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7f525b"

# Background color of selected item in processes box
theme[selected_bg]="#b70073"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#534248"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8b4c4c"

# Cpu box outline color
theme[cpu_box]="#857278"

# Memory/disks box outline color
theme[mem_box]="#857278"

# Net up/down box outline color
theme[net_box]="#857278"

# Processes box outline color
theme[proc_box]="#857278"

# Box divider line and small boxes line color
theme[div_line]="#d8c1c8"

# Temperature graph colors
theme[temp_start]="#7f525b"
theme[temp_mid]="#b70073"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#7f525b"
theme[cpu_mid]="#b70073"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#7f525b"
theme[free_mid]=""
theme[free_end]="#ffd9df"

# Mem/Disk cached meter
theme[cached_start]="#8b4c4c"
theme[cached_mid]=""
theme[cached_end]="#ffdad8"

# Mem/Disk available meter
theme[available_start]="#b70073"
theme[available_mid]=""
theme[available_end]="#ffd8e6"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#7f525b"
theme[download_mid]="#b70073"
theme[download_end]="#8b4c4c"

# Upload graph colors
theme[upload_start]="#7f525b"
theme[upload_mid]="#b70073"
theme[upload_end]="#8b4c4c"