# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#22191b"

# Title color for boxes
theme[title]="#8e4958"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#75565b"

# Background color of selected item in processes box
theme[selected_bg]="#8e4958"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#524345"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#7a5832"

# Cpu box outline color
theme[cpu_box]="#847375"

# Memory/disks box outline color
theme[mem_box]="#847375"

# Net up/down box outline color
theme[net_box]="#847375"

# Processes box outline color
theme[proc_box]="#847375"

# Box divider line and small boxes line color
theme[div_line]="#d6c2c4"

# Temperature graph colors
theme[temp_start]="#75565b"
theme[temp_mid]="#8e4958"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#75565b"
theme[cpu_mid]="#8e4958"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#75565b"
theme[free_mid]=""
theme[free_end]="#ffd9de"

# Mem/Disk cached meter
theme[cached_start]="#7a5832"
theme[cached_mid]=""
theme[cached_end]="#ffddbb"

# Mem/Disk available meter
theme[available_start]="#8e4958"
theme[available_mid]=""
theme[available_end]="#ffd9de"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#75565b"
theme[download_mid]="#8e4958"
theme[download_end]="#7a5832"

# Upload graph colors
theme[upload_start]="#75565b"
theme[upload_mid]="#8e4958"
theme[upload_end]="#7a5832"