# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#26181a"

# Title color for boxes
theme[title]="#bc004e"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#82524c"

# Background color of selected item in processes box
theme[selected_bg]="#bc004e"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#544245"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8a4f34"

# Cpu box outline color
theme[cpu_box]="#877275"

# Memory/disks box outline color
theme[mem_box]="#877275"

# Net up/down box outline color
theme[net_box]="#877275"

# Processes box outline color
theme[proc_box]="#877275"

# Box divider line and small boxes line color
theme[div_line]="#dac0c3"

# Temperature graph colors
theme[temp_start]="#82524c"
theme[temp_mid]="#bc004e"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#82524c"
theme[cpu_mid]="#bc004e"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#82524c"
theme[free_mid]=""
theme[free_end]="#ffdad5"

# Mem/Disk cached meter
theme[cached_start]="#8a4f34"
theme[cached_mid]=""
theme[cached_end]="#ffdbcd"

# Mem/Disk available meter
theme[available_start]="#bc004e"
theme[available_mid]=""
theme[available_end]="#ffd9de"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#82524c"
theme[download_mid]="#bc004e"
theme[download_end]="#8a4f34"

# Upload graph colors
theme[upload_start]="#82524c"
theme[upload_mid]="#bc004e"
theme[upload_end]="#8a4f34"