background = {{colors.surface.default.rgba | to_color | set_alpha: 0.85 }}
base = {{colors.surface_container.default.rgba | to_color | set_alpha: 0.9 }}
text = {{colors.on_surface_variant.default.rgba | to_color | set_alpha: 0.9 }}
alternate_base = {{colors.surface_container_low.default.rgba | to_color | set_alpha: 0.9 }}
bright_text = {{colors.on_surface.default.rgba | to_color | set_alpha: 1 }}
accent = {{colors.primary.default.rgba | to_color | set_alpha: 0.9 }}
accent_secondary = {{colors.secondary.default.rgba | to_color | set_alpha: 0.9 }}

font_family = Readex Pro
font_family_monospace = AnonymicePro Nerd Font Mono

