rootcolor={{colors.background.default.hex_stripped}}ff

bordercolor={{colors.outline_variant.default.hex_stripped}}ff

splitcolor={{colors.outline_variant.default.hex_stripped}}ff

focuscolor={{colors.primary.default.hex_stripped}}ff

dropcolor={{colors.inverse_primary.default.hex_stripped}}ff

maximizescreencolor={{colors.secondary.default.hex_stripped}}ff

urgentcolor={{colors.error.default.hex_stripped}}ff

scratchpadcolor={{colors.tertiary.default.hex_stripped}}ff

globalcolor={{colors.secondary.default.hex_stripped}}ff

overlaycolor={{colors.tertiary.default.hex_stripped}}ff
