legacy_layout=false

background_color={{colors.surface_container_low.default.hex_stripped}}
text_color={{colors.on_surface.default.hex_stripped}}
text_outline_color={{colors.shadow.default.hex_stripped}}
battery_color={{colors.primary.default.hex_stripped}}

gpu_color={{colors.tertiary.default.hex_stripped}}
gpu_load_color={{colors.on_surface.default.hex_stripped}},{{colors.primary_fixed.default.hex_stripped}},{{colors.error.default.hex_stripped}}
vram_color={{colors.tertiary.default.hex_stripped}}

cpu_color={{colors.secondary.default.hex_stripped}}
cpu_load_color={{colors.on_surface.default.hex_stripped}},{{colors.primary_fixed.default.hex_stripped}},{{colors.error.default.hex_stripped}}
ram_color={{colors.secondary.default.hex_stripped}}

engine_color={{colors.primary.default.hex_stripped}}
frametime_color={{colors.primary.default.hex_stripped}} 

media_player_color={{colors.tertiary.default.hex_stripped}}
network_color={{colors.tertiary.default.hex_stripped}}

text_outline_thickness=1
background_alpha=0.2
alpha=0.85
round_corners=5
cellpadding_y=-0.05
font_file=/usr/share/fonts/TTF/AnonymiceProNerdFontPropo-Bold.ttf
font_size=12
font_size_secondary=10
font_scale_media_player=0.78
position=bottom-left
toggle_hud=Shift_R+F12
hud_compact
table_columns=3

vsync=4
output_folder=/home/zek/Documents/mangohud-logs
log_duration=30
log_interval=100
toggle_logging=Shift_L+F2
upload_logs

blacklist=pamac-manager,lact,ghb,bitwig-studio,ptyxis,yumex

battery
battery_time

gpu_text=GPU
gpu_stats
gpu_load_change
gpu_load_value=50,90
gpu_list=0
vram
gpu_core_clock
gpu_temp

cpu_text=CPU
cpu_stats
core_bars
cpu_load_change
cpu_load_value=50,90
cpu_mhz
cpu_temp
cpu_power

ram
swap

fps
fps_metrics=avg,0.01
frame_timing
fps_limit_method=early
toggle_fps_limit=Shift_L+F1
fps_limit=0
#offset=0

display_server
resolution
gamemode
vkbasalt
winesync
network=wlan0

media_player
media_player_format=now playing:;{artist} - {title};{album}
